default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      project: "DeathDPI.xcodeproj",
      scheme: "DeathDPI",
      devices: ["iPhone 13"]
    )
  end

  desc "Build app"
  lane :build do
    build_ios_app(
      project: "DeathDPI.xcodeproj",
      scheme: "DeathDPI",
      export_method: "development"
    )
  end
end 