disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - private_outlet
  - sorted_imports
  
excluded:
  - Pods
  - DeathDPITests
  - DeathDPIUITests
  
force_cast: warning
force_try: warning 
